In [9]:
import numpy as npx=int(input("X = "))
y=int(input("Y = "))
z=np.zeros((x,y))
for r in range(x):
  for c in range(y):
    z[r,c]=r*c
print(z)


X = 3
Y = 3
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
